# MicroVerse — SPEC section 20.
#
# The image installs requirements.lock.txt, not requirements.txt: the latter is a set of
# lower bounds, so installing it directly would put whatever PyPI served on build day
# into the image instead of the versions the tests ran against. The lock is generated by
# deploy/lock_requirements.py, which resolves for this exact base image, checks every
# entry is a wheel (so the image needs no compiler) and refuses to emit a pre-release.
# Regenerate it whenever requirements.txt changes; CI fails if it is stale.
#
# Two stages: the builder installs and runs the test suite, and only its site-packages
# and the application source reach the runtime layer. A broken engine cannot ship,
# and pytest, ruff and the test fixtures do not travel to production.

# ---------------------------------------------------------------------------
FROM python:3.12-slim AS builder

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

WORKDIR /srv

COPY requirements.txt requirements.lock.txt ./
RUN pip install --no-cache-dir --prefix=/install -r requirements.lock.txt

COPY app ./app
COPY examples ./examples
COPY tests ./tests
COPY MICROVERSE_SPEC_v2_idea2.md CONTRIBUTING.md README.md pyproject.toml ./

# docs/ holds the experiment records the tests check the application's hard-coded
# constants against. Without it the suite this build gates on cannot run as
# written: one test reads docs/benchmark.json outright, and test_evidence.py's
# drift checks skip themselves -- which is the gate quietly losing a test rather
# than failing. 1.1 MB, and the builder stage only; the runtime does not need it.
COPY docs ./docs

# The same is true of the deployment checks: they read vercel.json, .gitignore and the
# Blob signing service's source, to assert the host is configured to find what it needs
# and that the Python and JavaScript sides agree. Without them nine tests fail and the
# gate stops the build. Builder stage only; the runtime serves none of them.
COPY vercel.json .gitignore ./
COPY blob/api ./blob/api

# Generate the demo datasets at build time so the landing page works offline.
ENV PYTHONPATH=/install/lib/python3.12/site-packages
RUN python examples/make_examples.py

# Fail the build if the engine is wrong, rather than shipping it.
RUN python -m pytest tests -q --no-header -x

# ---------------------------------------------------------------------------
FROM python:3.12-slim AS runtime

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    MICROVERSE_DATA=/data \
    PORT=8000 \
    WEB_CONCURRENCY=1 \
    PATH="/install/bin:${PATH}" \
    PYTHONPATH=/install/lib/python3.12/site-packages

# A research service parsing untrusted uploads has no business running as root.
# Fixed uid/gid so a mounted volume's ownership is predictable across hosts.
RUN groupadd --gid 10001 microverse \
 && useradd --uid 10001 --gid 10001 --no-create-home --shell /usr/sbin/nologin microverse

WORKDIR /srv

COPY --from=builder /install /install
COPY --from=builder /srv/app ./app
COPY --from=builder /srv/examples ./examples
COPY --from=builder /srv/MICROVERSE_SPEC_v2_idea2.md /srv/README.md ./
COPY deploy/entrypoint.sh /usr/local/bin/entrypoint.sh

RUN mkdir -p /data \
 && chown -R microverse:microverse /data /srv \
 && chmod +x /usr/local/bin/entrypoint.sh

USER microverse

EXPOSE 8000
VOLUME ["/data"]

# start-period covers first-run database creation; the check itself is the same
# endpoint the load balancer should use.
HEALTHCHECK --interval=30s --timeout=5s --start-period=25s --retries=3 \
  CMD python -c "import os,urllib.request,sys; \
sys.exit(0 if urllib.request.urlopen(f'http://127.0.0.1:{os.environ.get(\"PORT\", 8000)}/healthz', timeout=4).status == 200 else 1)"

# Exec form so uvicorn is PID 1 and receives SIGTERM directly — an in-flight analysis
# gets the graceful-shutdown window instead of being killed.
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
