"""Resolve requirements.txt for the container's platform and write requirements.lock.txt.

The Dockerfile installed `requirements.txt` directly, which is a set of lower bounds.
That is fine for a dev checkout and wrong for a shipped image: the versions in the image
are then whatever PyPI served on build day, and the image stops matching what the tests
ran against. It also let a *pre-release* in — `formulaic` declares
`wrapt>=1.17.0rc1; python_version >= "3.13"`, and a specifier containing `rc1` switches
pre-releases on for that project, so a plain resolve picked `wrapt 2.4.1rc1` over the
stable 2.4.0.

This resolves once, for the image's exact platform, and writes exact pins. It refuses to
write a lock containing a pre-release, so that class of drift cannot come back silently.

    .venv/Scripts/python deploy/lock_requirements.py
    .venv/Scripts/python deploy/lock_requirements.py --check   # CI: fail if stale

Hashes are deliberately not emitted. A `--require-hashes` lock would have to name one
platform's wheels, which would break `docker build` on arm64; exact version pins are
reproducible and stay architecture-portable.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REQUIREMENTS = os.path.join(ROOT, "requirements.txt")
LOCKFILE = os.path.join(ROOT, "requirements.lock.txt")
CONSTRAINTS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "constraints.txt")

#: Must match the Dockerfile's base image.
PYTHON_VERSION = "3.12"
PLATFORM = "manylinux2014_x86_64"

HEADER = f"""\
# Generated by deploy/lock_requirements.py — do not edit by hand.
#
# Exact versions the container image installs, resolved from requirements.txt for
# Python {PYTHON_VERSION} on {PLATFORM}. Regenerate after changing requirements.txt:
#
#     python deploy/lock_requirements.py
#
# Every entry resolves to a binary wheel, so the image needs no compiler.
"""


def _is_prerelease(version: str) -> bool:
    for marker in ("a", "b", "rc", "dev"):
        head, sep, tail = version.partition(marker)
        if sep and head and head[-1].isdigit() and tail[:1].isdigit():
            return True
    return False


def resolve() -> list:
    """Ask pip to resolve for the image's platform and report what it would install."""
    with tempfile.TemporaryDirectory() as workdir:
        report_path = os.path.join(workdir, "report.json")
        command = [
            sys.executable, "-m", "pip", "install",
            "--dry-run", "--quiet",
            "--report", report_path,
            "--target", os.path.join(workdir, "target"),
            "--python-version", PYTHON_VERSION,
            "--platform", PLATFORM,
            "--only-binary=:all:",
            "-r", REQUIREMENTS,
        ]
        if os.path.exists(CONSTRAINTS):
            command += ["-c", CONSTRAINTS]
        completed = subprocess.run(command, capture_output=True, text=True, check=False)
        if completed.returncode != 0:
            sys.stderr.write(completed.stdout + completed.stderr)
            raise SystemExit(f"pip could not resolve requirements.txt for "
                             f"{PLATFORM}/py{PYTHON_VERSION}")
        with open(report_path, encoding="utf-8") as handle:
            report = json.load(handle)

    packages = []
    for item in report["install"]:
        metadata = item["metadata"]
        url = item["download_info"]["url"]
        packages.append((metadata["name"], metadata["version"], url))
    return sorted(packages, key=lambda p: p[0].lower())


def render(packages: list) -> str:
    lines = [HEADER]
    for name, version, _ in packages:
        lines.append(f"{name}=={version}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="fail if the lock is missing or out of date")
    args = parser.parse_args()

    packages = resolve()

    source_builds = [n for n, _, url in packages if not url.endswith(".whl")]
    if source_builds:
        print("These would need a compiler in the image: " + ", ".join(source_builds))
        return 1

    prereleases = [(n, v) for n, v, _ in packages if _is_prerelease(v)]
    if prereleases:
        print("Refusing to write a lock containing pre-releases:")
        for name, version in prereleases:
            print(f"    {name} {version}")
        print(f"\nAdd a stable bound to {os.path.relpath(CONSTRAINTS, ROOT)} and rerun.")
        return 1

    rendered = render(packages)
    existing = None
    if os.path.exists(LOCKFILE):
        with open(LOCKFILE, encoding="utf-8") as handle:
            existing = handle.read()

    if args.check:
        if existing is None:
            print(f"{os.path.relpath(LOCKFILE, ROOT)} does not exist — run "
                  "python deploy/lock_requirements.py")
            return 1
        if existing != rendered:
            print(f"{os.path.relpath(LOCKFILE, ROOT)} is out of date — run "
                  "python deploy/lock_requirements.py")
            return 1
        print(f"{os.path.relpath(LOCKFILE, ROOT)} is up to date "
              f"({len(packages)} packages).")
        return 0

    with open(LOCKFILE, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(rendered)
    print(f"wrote {os.path.relpath(LOCKFILE, ROOT)} — {len(packages)} packages, "
          f"all wheels, no pre-releases")
    return 0


if __name__ == "__main__":
    sys.exit(main())
