"""Record the v2 engine's outputs on the demos, so v3 can prove it still produces them.

v3 (docs/MICROVERSE_V3_PLAN.md §26.5) requires that with the v2 rule set and uniform
weights every v2 output is byte-identical. That is only a meaningful test if the
reference was written by v2 itself, before any v3 code existed: these files were
generated at commit 8d1cd9f and are not to be regenerated by v3 code. If a v2 output
ever has to change on purpose, regenerate them from the commit that changes it and say
why in docs/V3_DEVIATIONS.md.

The record is per platform and Python version. The same v2 engine does not write the
same bytes on Windows and Linux: pandas ends CSV lines with the platform's separator
(CRLF against LF), and in covariate mode the linear algebra differs in the last bits,
enough to move 3 of 2,016 p-values for one taxon across 0.05. Nor does it on one
platform under two Python versions: CI's Python 3.12 and 3.13 jobs failed against the
Linux set that its 3.14 job reproduced, with the same pinned packages. So sha256.json
holds one set of hashes per `platform_key()` ("linux-py3.14"), each written by 8d1cd9f
in that environment, and the test compares against its own environment's set and skips,
saying so, where none was recorded. The readable copies beside it are the Linux output.
The Windows set is the first one recorded; the Linux set was written from a worktree at
8d1cd9f with this script copied in and the `ruleset=` argument removed
(docs/V3_DEVIATIONS.md).

Recorded hashes only hold while the environment holds. CI's Python 3.14 runner moved on
and `results_long.csv` stopped matching the Linux set, so its hashes were dropped (B1b):
CI instead runs tests/reference/compare_v2_engine.py, which runs the v2 engine and this
tree side by side in one environment. The Windows set stays for local checks.

    python tests/fixtures/make_v2_golden.py
"""
from __future__ import annotations

import gzip
import hashlib
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, ROOT)

OUT = os.path.join(HERE, "v2_golden")

#: (demo, mode). Covariate mode varies the adjustment set over the demo's covariates.
CASES = (("ibd_genus", "quick"), ("gut_species", "quick"), ("t2d_covariates", "covariate"))


def outputs(demo: str, mode: str, ruleset: str = "v2") -> dict:
    """Every v2 output a researcher can download, as bytes, for one demo run.

    The files were written before `ruleset` existed, by an engine that only had v2's
    rules; passing "v2" is what reproduces that engine now.
    """
    from app.core.attribution import attribute
    from app.core.report import (
        attribution_csv,
        long_results_csv_gz,
        robustness_csv,
        specifications_csv,
    )
    from app.core.robustness import compute_robustness, verdict_sentence
    from app.core.runner import run_multiverse
    from app.services import load_demo

    dataset = load_demo(demo)
    covariates = list(dataset.covariate_columns) if mode == "covariate" else ()
    run = run_multiverse(dataset, mode=mode, covariate_columns=covariates, ruleset=ruleset)
    summary = compute_robustness(run)
    attribution = attribute(run)
    return {
        "robustness.csv": robustness_csv(summary),
        "specifications.csv": specifications_csv(run, summary),
        "results_long.csv": gzip.decompress(long_results_csv_gz(run)),
        "attribution.csv": attribution_csv(attribution),
        "verdict.txt": verdict_sentence(run, summary).encode("utf-8"),
        "grid.json": json.dumps({
            "n_enumerated": run.grid_report.n_enumerated,
            "n_valid": run.grid_report.n_valid,
            "n_pruned": run.grid_report.n_pruned,
            "pruned_reasons": run.grid_report.pruned_reasons,
            "tier_counts": summary.tier_counts,
        }, indent=2, sort_keys=True).encode("utf-8"),
    }


def platform_key(platform: str = sys.platform, version=sys.version_info) -> str:
    """The environment a record belongs to: platform and Python minor version."""
    return f"{platform}-py{version[0]}.{version[1]}"


def expected_hashes(key: str = None) -> dict:
    """This environment's recorded hashes, or {} if 8d1cd9f was never run in it."""
    path = os.path.join(OUT, "sha256.json")
    if not os.path.exists(path):
        return {}
    with open(path, encoding="utf-8") as handle:
        return json.load(handle).get("platforms", {}).get(key or platform_key(), {})


def main() -> None:
    os.makedirs(OUT, exist_ok=True)
    index = {}
    for demo, mode in CASES:
        folder = os.path.join(OUT, f"{demo}_{mode}")
        os.makedirs(folder, exist_ok=True)
        for name, data in outputs(demo, mode).items():
            digest = hashlib.sha256(data).hexdigest()
            index[f"{demo}_{mode}/{name}"] = digest
            # The long table is megabytes; its hash is the record. The rest is small
            # enough to keep, so a failure can be read as a diff rather than a hash.
            if name != "results_long.csv" and sys.platform == "linux":
                with open(os.path.join(folder, name), "wb") as handle:
                    handle.write(data)
        print(f"{demo} {mode}: recorded for {platform_key()}")
    path = os.path.join(OUT, "sha256.json")
    record = {"platforms": {}}
    if os.path.exists(path):
        with open(path, encoding="utf-8") as handle:
            record = json.load(handle)
    record["platforms"][platform_key()] = index
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        json.dump(record, handle, indent=2, sort_keys=True)
        handle.write("\n")


if __name__ == "__main__":
    main()
